#
#  aHCF HCF Core
#
# Coded by ZeflyYT, Emirate
#
# Report Bugs at
#
# Discord: Zefly#4954 or Emirate#9246
#
HWID: ''
Scoreboard_title: '&3&laHCF &7| &fHCF'
Kitmap:
  Sharpness: 1
  Protection: 1
kits-mode: false
block-in-combat: true
tab-list: false
SERVER_NAME: aHCF
DONATE_URL: ahcf.com
top-rank: TOPRANK
Footer:
  Permit: True
  Footer-Text: "&7&oahcf.com"
SPAWN_NO_BREAK_RADIUS: 150
WARZONE_RADIUS: 150
NETHER_WARZONE_RADIUS: 300
Scoreboard:
  Kills:
    Name: '&fKills&7: &6%kills%'
  Deaths:
    Name: '&fDeaths&7: &6%deaths%'
  Staffboard:
    Name: '&6Staff Mode'
  Vanish:
    Name: ' &e» &fVanish&7: &f%vanish%'
  StaffChat:
    Name: " &e» &fStaffChat&7: &f%staffchat%"  
MAX-FACTION: 25
MAX-ALLY: 0
Colours:
 PRIMARY-COLOR: '&3&l'
 SECONDARY-COLOR: '&b'
 TIMER-COLOR: '&e'
DEFAULT_DEATHBAN_DURATION: 3600000
WILDERNESS_COLOUR: DARK_GREEN
WARZONE_COLOUR: RED
SAFEZONE_COLOUR: AQUA
TEAMMATE_COLOUR: DARK_GREEN
ALLY_COLOUR: BLUE
ENEMY_COLOUR: RED
ROAD_COLOUR: GOLD
GLOWSTONE_COLOUR: GOLD
COMBATLOG_DESPAWN_DELAY_TICKS: 300
potionLimits:
  STRENGTH: 0
  INVISIBILITY: 1
  REGEN: 0
  WEAKNESS: 0
  INSTANT_DAMAGE: 0
  SLOWNESS: 1
  POISON: 1
potionsExtendedDisallowed:
  POISON
  SLOWNESS
Help:
- '&8&m------------------------------------'
- '&2&lMap Infomation&7:'
- '&7Current Map&8 - &fMap 1'
- '&7Map Border&8 - &f3000'
- '&7Map Kit&8 - &f/mapkit'
- '&8&m------------------------------------'
- '&2&lUseful Commands&7:'
- '&7/coords - &fProvides the coordinates for KoTH Locations'
- '&7/teamspeak - &fProvides the Teamspeak Server IP'
- '&7/mapkit - &fProvides you with the Map Information on Enchant Limits and Potions'
- '&7/report <Player> <Reason> - &fA command to report rule-breakers'
- '&7/helpop <Message> - &fAlerts online Staff Members that you are in need of
  assistance'
- '&8&m------------------------------------'
- '&2&lOther infomation&7:'
- '&7Website&8 - &fwww.ahcf.com'
- '&7Buycraft&8 - &fstore.ahcf.com'
- '&7Teamspeak&8 - &fts.ahcf.com'
- '&8&m------------------------------------'
Teamspeak:
- '&7Teamspeak: &fts.server.net'
teamspeak-frozen: ts.server.net
Coords:
- '&8&m----------------------------------------'
- '&2&lCoords'
- '&7Spawn: &70,0 &7(Overworld)'
- '&7Nether Spawn: &70,0 &7(Nether)'
- '&7EndPortals: &70,1500,0 &7(All for quads)'
- '&8&m----------------------------------------'
Online-Donator-Broadcast:
- ''
- '&3&lDONOR PLAYERS &6>> %player%'
- '&7If you wanna be shown on here donate at store.ahcf.me'
- ''
spawn:
  world: world
  x: 0.538049846829157
  y: 69.0
  z: 0.6617853658512408
  yaw: 0.78689575
  pitch: 11.715501
